Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
AllCops:
  Exclude:
    - config/**/*
    - bin/**/*
    - Gemfile
    - test/**/*
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Metrics/MethodLength:
  Exclude:
    - db/**/*
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - db/schema.rb
Style/StringLiterals:
  Exclude:
    - spec/**/*
    - db/schema.rb
Style/NumericLiterals:
  Exclude:
    - db/**/*
Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb
    - spec/rails_helper.rb
Metrics/BlockLength:
  Exclude:
    - spec/**/*